### ISSUE TITLE
Provide more information about zookeeper server in case of connection errors

### ISSUE THREAD

**Issue by oneiros-de** [sgroschupf/zkclient#41]
I'm trying to track down a connection problem. The only information I have is basically a stacktrace that ends with `Factory method 'consumerController' threw exception; nested exception is org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 4000`

Please provide more information about the server here, like name and port.

**Comment by jzillmann** [comment]
Pushed a change into master.
Old message: 
```
Unable to connect to zookeeper server within timeout: 500
```
New message:
```
Unable to connect to zookeeper server 'localhost:4711' with timeout of 500 ms
```

Thanks for reporting!
