### ISSUE TITLE
gradle 2.x

### ISSUE THREAD

**Issue by puntogil** [sgroschupf/zkclient#49]
Hi
can you provide a settings(.gradle) file with the following content:
rootProject.name="zkclient"
the reasons of this request are explained here
https://discuss.gradle.org/t/rootproject-name-in-settings-gradle-vs-projectname-in-build-gradle/5704/2
I used for fix: echo 'rootProject.name="zkclient"' >> settings.gradle
Regards
Thanks in advance

**Comment by jzillmann** [comment]
Fixed in master
