### ISSUE TITLE
Source file without license header

### ISSUE THREAD

**Issue by puntogil** [sgroschupf/zkclient#51]
Hi
The following source file are without license header:
./src/test/java/org/I0Itec/zkclient/ZkStateChangeTest.java
Please, confirm the licensing of code and/or content/s, and add license headers
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification
Thanks in advance
Regards

**Comment by fpj** [comment]
I've created a pull request for this issue.

**Comment by jzillmann** [comment]
This has been merged a while ago!
